// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjovdetovqnriqtovfaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb3ZkZXRvdnFucmlxdG92ZmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NDI4ODAsImV4cCI6MjA1NDMxODg4MH0.VzoA-jBgCjWP4pAygL1Rl30o3EbcHw4FSuNv0dvDuis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);